melihat_informasi_beasiswa_aktif/urls.py
from django.conf.urls import url
from .views import index, detail_beasiswa
from daftar_calon_penerima_beasiswa.views import indexKodeBeasiswa

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<kode_beasiswa>.*)/daftar', indexKodeBeasiswa, name='indexKodeBeasiswa' ),
    url(r'^(?P<kode>.*)/(?P<no_urut>.*)', detail_beasiswa, name='detail-beasiswa'),
]

simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login_logout.urls as login
import register.urls as register
from login_logout.views import auth_logout
import melihat_informasi_beasiswa_aktif.urls as melihat_informasi_beasiswa_aktif
import mendaftarkan_skema_beasiswa.urls as mendaftarkan_skema_beasiswa
import daftar_calon_penerima_beasiswa.urls as daftar_calon_penerima_beasiswa
import tentukan_status_calon.urls as tentukan_status_calon

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^beasiswa_aktif/', include(('melihat_informasi_beasiswa_aktif.urls','melihat_informasi_beasiswa_aktif'), namespace='melihat-informasi-beasiswa-aktif')),
    url(r'^daftarkan_beasiswa/', include(('mendaftarkan_skema_beasiswa.urls', 'mendaftarkan_skema_beasiswa'), namespace='mendaftarkan-skema-beasiswa')),
    url(r'^$', RedirectView.as_view(url = "/beasiswa_aktif/", permanent = "true"), name = 'index'),
    url(r'^daftar-calon-penerima-beasiswa/', include(('daftar_calon_penerima_beasiswa.urls', 'daftar_calon_penerima_beasiswa'), namespace='daftar-calon-penerima-beasiswa')),
    url(r'^list-beasiswa/', include(('tentukan_status_calon.urls', 'tentukan_status_calon'), namespace='list-beasiswa')),
    url(r'^login/', include(('login_logout.urls', 'login'), namespace="login")),
    url(r'^logout/', auth_logout, name="logout"),
    url(r'^register/', include(('register.urls', 'register'),namespace="register"))
]

melihat_informasi_beasiswa_aktif/models.py
from django.db import models

# Create your models here.

melihat_informasi_beasiswa_aktif/views.py
from django.shortcuts import render
from django.db import connection
from mendaftarkan_skema_beasiswa.models import Beasiswa
from tentukan_status_calon.models import SkemaBeasiswaAktif
# Create your views here.
response = {}
cursor = connection.cursor()
def index(request):
	if("username" not in request.session):
		response['not_logged_in'] = True
	else:
		response['not_logged_in'] = False
		username = request.session['username']
		response['username'] = username
		query = "SELECT * FROM pengguna WHERE username='"+username+"'"
		cursor.execute(query)
		select = dictfetchall(cursor)
		print(select[0]['role'])

		role = select[0]['role']
		if role == 'donatur':
			response['donatur'] = True
			response['mahasiswa'] = False
		else:
			response['mahasiswa'] = True
			response['donatur'] = False

	cursor.execute("SELECT * FROM skema_beasiswa")
	select = dictfetchall(cursor)
	response['beasiswaAsli'] = select

	cursor.execute("SELECT * FROM skema_beasiswa_aktif")
	select = dictfetchall(cursor)
	response['beasiswa'] = select
	return render(request, 'melihat_informasi_beasiswa_aktif/index.html', response)

def detail_beasiswa(request, kode, no_urut):
	if("username" not in request.session):
		response['not_logged_in'] = True
	else:
		response['not_logged_in'] = False
		username = request.session['username']
		query = "SELECT * FROM pengguna WHERE username='"+username+"'"
		cursor.execute(query)
		select = dictfetchall(cursor)
		print(select[0]['role'])

		role = select[0]['role']
		if role == 'donatur':
			response['donatur'] = True
			response['mahasiswa'] = False
		elif role == 'mahasiswa' :
			response['mahasiswa'] = True
			response['donatur'] = False

	query = "SELECT * FROM skema_beasiswa WHERE kode='"+kode+"'"
	cursor.execute(query)
	select = dictfetchall(cursor)
	response['beasiswa'] = select[0]

	query = "SELECT * FROM skema_beasiswa_aktif WHERE kode_skema_beasiswa='"+kode+"' AND no_urut='"+no_urut+"'"
	cursor.execute(query)
	select = dictfetchall(cursor)
	response['beasiswaAktif'] = select[0]

	query = "SELECT * FROM syarat_beasiswa WHERE kode_beasiswa='"+kode+"'"
	cursor.execute(query)
	select = dictfetchall(cursor)
	response['beasiswaSyarat'] = select[0]
	return render(request, 'melihat_informasi_beasiswa_aktif/detail.html', response)

def dictfetchall(cursor):
	"Return all rows from a cursor as a dict"
	columns = [col[0] for col in cursor.description]
	return [
		dict(zip(columns, row))
		for row in cursor.fetchall()
	]

melihat_informasi_beasiswa_aktif/templates/melihat_informasi_beasiswa_aktif/detail.html
{% extends "melihat_informasi_beasiswa_aktif/layout/base.html" %}
{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="align-self-center col-md-6 text-white">
      <h1 class="text-center text-md-left display-4" style="color: black;">{{beasiswa.nama}}</h1>
      <p class="lead" style="color: black;">{{beasiswa.kode}}</p>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body p-5">
          <h5>Jenis Beasiswa : {{beasiswa.jenis}}</h5>
          <h5>Nomor Identitas Donatur : {{beasiswa.no_identitas_donatur}}</h5>
          <p>{{beasiswa.deskripsi}}</p>
          <p>Syarat Beasiswa : {{beasiswaSyarat.syarat}}</p>
          <p>Status Beasiswa : {{beasiswaAktif.status}}</p>
          {% if beasiswaAktif.status == "Buka" %}
          {% if mahasiswa %}
          <a href="{% url 'melihat_informasi_beasiswa_aktif:indexKodeBeasiswa' beasiswa.kode %}" class="btn btn-lg btn-primary">Daftar</a>
          {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div> 
<br>
{% endblock %}

melihat_informasi_beasiswa_aktif/templates/melihat_informasi_beasiswa_aktif/index.html
{% extends "melihat_informasi_beasiswa_aktif/layout/base.html" %}
{% block content %}
<style type="text/css">
  .py-5{
    padding-top: 6em!important;
    padding-bottom: 6em!important;
  }
</style>
<div class="py-5 text-center backside" style="background-image: url(http://hibbing.edu//assets/images/0/meta/10-0.graduation-wallpapers.jpg);">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3 mb-4 text-primary">SIMBION</h1>
          <p class="lead mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
          {% if not_logged_in %} 
          <br><br>
          <a href="{% url 'login:index' %}" class="btn btn-lg btn-warning mx-1">Login/Register</a>
          {% else %}
          <a href="{% url 'daftar_calon_penerima_beasiswa:index' %}" class="btn btn-lg mx-1 btn-secondary">Daftar Beasiswa</a>
          {% endif %}
          <hr>
          <a href="{% url 'melihat_informasi_beasiswa_aktif:index'%}#lowongan " class="btn btn-lg btn-primary mx-1">List Lowongan</a>
        </div>
      </div>
    </div>
  </div>
  <div class="p-5 bg-secondary" id="lowongan">
    <h2 class="text-primary" align="middle">List Lowongan</h2>
    <hr>
      {% if beasiswa %}
      {% for b in beasiswa %}
      {% for bb in beasiswaAsli %}
      {% if b.kode_skema_beasiswa == bb.kode %}
      <div class="card">
        <div class="card-block p-4">
          <h5>{{bb.nama}} - {{b.kode_skema_beasiswa}}</h5>
          <h5>Periode penerimaan : {{b.periode_penerimaan}}</h5>
          <p>Status Beasiswa : {{b.status}}</p>
          <p>Jumlah Pendaftar : {{b.jumlah_pendaftar}}</p>
          <a href="{% url 'melihat_informasi_beasiswa_aktif:detail-beasiswa' b.kode_skema_beasiswa b.no_urut %}" class="btn btn-lg btn-primary">Lihat Detail</a>
        </div>
      </div>
      <br>
      {% endif %}
      {% endfor %}
      {% endfor %}
      {% endif %}
  </div>  
{% endblock %}