login_logout/urls.py
from django.conf.urls import url
from .views import index,auth_login, auth_logout

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^auth_login/$', auth_login, name="auth_login"),
    url(r'^auth_logout/$', auth_logout, name="auth_logout")

]

simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login_logout.urls as login
import register.urls as register
from login_logout.views import auth_logout
import melihat_informasi_beasiswa_aktif.urls as melihat_informasi_beasiswa_aktif
import mendaftarkan_skema_beasiswa.urls as mendaftarkan_skema_beasiswa
import daftar_calon_penerima_beasiswa.urls as daftar_calon_penerima_beasiswa
import tentukan_status_calon.urls as tentukan_status_calon

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^beasiswa_aktif/', include(('melihat_informasi_beasiswa_aktif.urls','melihat_informasi_beasiswa_aktif'), namespace='melihat-informasi-beasiswa-aktif')),
    url(r'^daftarkan_beasiswa/', include(('mendaftarkan_skema_beasiswa.urls', 'mendaftarkan_skema_beasiswa'), namespace='mendaftarkan-skema-beasiswa')),
    url(r'^$', RedirectView.as_view(url = "/beasiswa_aktif/", permanent = "true"), name = 'index'),
    url(r'^daftar-calon-penerima-beasiswa/', include(('daftar_calon_penerima_beasiswa.urls', 'daftar_calon_penerima_beasiswa'), namespace='daftar-calon-penerima-beasiswa')),
    url(r'^list-beasiswa/', include(('tentukan_status_calon.urls', 'tentukan_status_calon'), namespace='list-beasiswa')),
    url(r'^login/', include(('login_logout.urls', 'login'), namespace="login")),
    url(r'^logout/', auth_logout, name="logout"),
    url(r'^register/', include(('register.urls', 'register'),namespace="register"))
]

login_logout/models.py
from django.db import models

# Create your models here.

login_logout/views.py
from django.shortcuts import render
from mendaftarkan_skema_beasiswa.models import Beasiswa
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connection, connections

# Create your views here.
response = {}
def index(request):
    if("username" not in request.session):
        return render(request, 'login_logout/index.html', response)
    else:
        return HttpResponseRedirect(reverse('melihat_informasi_beasiswa_aktif:index'))


def auth_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        cursor = connection.cursor()
        query = "select username, role from pengguna where username = '" + username + "' and password = '" + password + "'"
        cursor.execute(query)

        result = cursor.fetchone()
        print(result)

        if(result is not None):
            request.session["username"] = result[0]
            request.session["role"] = result[0]

        return HttpResponseRedirect(reverse('login:index'))

def auth_logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('melihat_informasi_beasiswa_aktif:index'))

login_logout/templates/login_logout/index.html
{% extends "melihat_informasi_beasiswa_aktif/layout/base.html" %}
{% block content %}
    <style>

        *{
            font-family: 'Droid Sans', sans-serif;
        }
        .main{
            text-align: center;
            height: 725px;
        }

        .main h2{
            font-size: 50px;
            margin-top: 0px;
            padding-top: 125px;
        }

        .font_form{
            font-size: 25px;
        }

        .main form h5{
            font-size: 25px;
        }

        .main h5{
            font-size: 20px;
        }

    </style>

    <div class="main">

            <h2><strong>Simbion</strong></h2>

            <br><br>

            <form style="font-size: 25px; margin-top: 25px" action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                {% csrf_token %}
                <p>
                    <label for="username"> Username </label>
                    <input type="text" name="username" required>
                </p>
                <p>
                    <label for="password"> Password </label>
                    <input type="password" name="password" required>
                </p>
                <input type="submit" value = "Submit">
            </form>

            <h5 >Pengguna baru? <a href="{% url 'register:index'%}" class="btn btn-primary">Daftar sekarang</a></h5>

    </div>
{% endblock %}