register/urls.py
from django.conf.urls import url
from register.views import index, form_mhs, form_dp, form_dy, kategori \
    , reg_mhs, reg_dp, reg_dy
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^kategori/(?P<kategori>\d+)/$',kategori,name="kategori"),
    url(r'^form_mhs/$',form_mhs,name='form_mhs'),
    url(r'^form_dp/$',form_dp,name='form_dp'),
    url(r'^form_dy/$',form_dy,name='form_dy'),
    url(r'^reg_mhs/$',reg_mhs,name='reg_mhs'),
    url(r'^reg_dp/$',reg_dp,name='reg_dp'),
    url(r'^reg_dy/$',reg_dy,name='reg_dy'),
]

simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login_logout.urls as login
import register.urls as register
from login_logout.views import auth_logout
import melihat_informasi_beasiswa_aktif.urls as melihat_informasi_beasiswa_aktif
import mendaftarkan_skema_beasiswa.urls as mendaftarkan_skema_beasiswa
import daftar_calon_penerima_beasiswa.urls as daftar_calon_penerima_beasiswa
import tentukan_status_calon.urls as tentukan_status_calon

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^beasiswa_aktif/', include(('melihat_informasi_beasiswa_aktif.urls','melihat_informasi_beasiswa_aktif'), namespace='melihat-informasi-beasiswa-aktif')),
    url(r'^daftarkan_beasiswa/', include(('mendaftarkan_skema_beasiswa.urls', 'mendaftarkan_skema_beasiswa'), namespace='mendaftarkan-skema-beasiswa')),
    url(r'^$', RedirectView.as_view(url = "/beasiswa_aktif/", permanent = "true"), name = 'index'),
    url(r'^daftar-calon-penerima-beasiswa/', include(('daftar_calon_penerima_beasiswa.urls', 'daftar_calon_penerima_beasiswa'), namespace='daftar-calon-penerima-beasiswa')),
    url(r'^list-beasiswa/', include(('tentukan_status_calon.urls', 'tentukan_status_calon'), namespace='list-beasiswa')),
    url(r'^login/', include(('login_logout.urls', 'login'), namespace="login")),
    url(r'^logout/', auth_logout, name="logout"),
    url(r'^register/', include(('register.urls', 'register'),namespace="register"))
]

register/models.py
from django.db import models

# Create your models here.

register/views.py
from django.shortcuts import render
from mendaftarkan_skema_beasiswa.models import Beasiswa
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connection, connections


# Create your views here.
response = {}
def index(request):
    if("username" not in request.session):
        return render(request, 'register/index.html', response)
    else:
        return HttpResponseRedirect(reverse('melihat_informasi_beasiswa_aktif:index'))

def kategori(request, kategori):
    if(kategori == '1'):
        return HttpResponseRedirect(reverse('register:form_mhs'))
    elif(kategori == '2'):
        return HttpResponseRedirect(reverse('register:form_dp'))
    elif(kategori == '3'):
        return HttpResponseRedirect(reverse('register:form_dy'))

def form_mhs(request):
    return render(request, 'register/register_mahasiswa.html',response)

def form_dp(request):
    return render(request, 'register/register_donatur_pribadi.html',response)

def form_dy(request):
    return render(request, 'register/register_donatur_yayasan.html', response)

def reg_mhs(request):
    reg_pengguna(request.POST["username"],request.POST["password"],"mahasiswa")

    query = "INSERT INTO MAHASISWA(npm, email, nama, no_telp, alamat_tinggal, alamat_domisili, nama_bank, no_rekening, nama_pemilik, username) VALUES "+\
            "(" + request.POST["npm"] + ", '" + request.POST["email"] + "', '" + request.POST["nama_lengkap"] + "', " + request.POST["no_telp"] + ", '" + request.POST["alamat_t"] + "', '" +\
            request.POST["alamat_d"] + "', '" + request.POST["instansi_bank"] + "', " + request.POST["no_rek"] + ", '" + request.POST["nama_pemilik"] + "', '" + request.POST["username"] + "');"
    cursor = connection.cursor()
    cursor.execute(query)

    return HttpResponseRedirect(reverse('login:index'))

def reg_dp(request):
    reg_pengguna(request.POST["username"],request.POST["password"],"donatur")
    reg_donatur(request.POST["no_id"],request.POST["email"],request.POST["nama_lengkap"],request.POST["npwp"],
                request.POST["no_telp"],request.POST["alamat"],request.POST["username"])


    query = "INSERT INTO INDIVIDUAL_DONOR(nik, nomor_identitas_donatur) VALUES "+\
            "(" + request.POST["nik"] + "," + request.POST["no_id"] + ");"
    cursor = connection.cursor()
    cursor.execute(query)

    return HttpResponseRedirect(reverse('login:index'))

def reg_dy(request):
    reg_pengguna(request.POST["username"],request.POST["password"],"donatur")
    reg_donatur(request.POST["no_id"],request.POST["email"],request.POST["nama_cp"],request.POST["npwp"],
                request.POST["no_telp"],request.POST["alamat"],request.POST["username"])


    query = "INSERT INTO YAYASAN(no_sk_yayasan, email, nama, no_telp_cp, nomor_identitas_donatur) VALUES "+\
            "('" + request.POST["no_sk"] + "', '" + request.POST["email"] + "', '" + request.POST["nama_yayasan"] + "', " + request.POST["no_telp"] + ", " + request.POST["no_id"] + ");"
    cursor = connection.cursor()
    cursor.execute(query)


    return HttpResponseRedirect(reverse('login:index'))

def reg_pengguna(username, password, role):
    query = "INSERT INTO PENGGUNA(username, password, role) VALUES "+\
            "('" + username + "', '" + password + "', '" + role +"');"
    cursor = connection.cursor()
    cursor.execute(query)

def reg_donatur(no_id,email,nama,npwp,no_telp,alamat,username):
    query = "INSERT INTO DONATUR(nomor_identitas, email, nama, npwp, no_telp, alamat, username) VALUES "+\
            "(" + no_id + ", '" + email + "', '" + nama + "', " + npwp + ", " + no_telp + \
            ", '" + alamat + "', '" + username + "');"
    cursor = connection.cursor()
    cursor.execute(query)

register/templates/register/index.html
{% extends "melihat_informasi_beasiswa_aktif/layout/base.html" %}
{% block content %}
    <style>


        *{
            font-family: 'Droid Sans', sans-serif;
        }
        .main{
            text-align: center;
            min-height: 725px;
            padding-left: 75px;
            padding-right: 75px;
        }

        .main h2{
            font-size: 50px;
            margin-top: 0px;
            padding-top: 75px;
        }

        .font_form{
            font-size: 25px;
        }

        .main form h5{
            font-size: 25px;
        }

        .main h5{
            font-size: 18px;
        }

    </style>

    <div class="main">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <div>
            <h2><strong>Daftar Anggota SIMBION</strong></h2>
            <br><br>
            <h4>
                SIMBION merupakan Portal Beasiswa yang diperuntukkan bagi Mahasiswa-mahasiswa Universitas Indonesia.
                <br><br>
                Bagi para mahasiswa aktif Universitas Indonesia, anda dapat mendaftarkan akun SIMBION agar dapat mengajukan diri dalam skema-skema beasiswa yang ada.
                <br><br>
                Anda juga bisa mendaftar sebagai Donatur yang dapat membuka skema beasiswa sesuai keinginan anda, anda dapat mendaftar sebagai donatur pribadi maupun donatur yayasan.

            </h4>
        </div>

        <br><br>

        <div style="align-content: center">
            <div class="col-sm-4">
                <h1>Mahasiswa</h1>

                <h5>
                    Anda harus merupakan mahasiswa aktif terdaftar di Universitas Indonesia.
                    Setiap anggota yang hendak menganjukan pendaftaran beasiswa harus memenuhi syarat-syarat
                    yang telah ditentukan oleh masing-masing skema beasiswa.
                    <br><br>
                    Silakan klik link dibawah ini untuk mendaftarkan diri
                </h5>

                <h4><strong><a class="btn btn-primary" href="{% url 'register:kategori' 1 %}">Daftar sebagai Mahasiswa</a></strong></h4>
            </div>

            <div class="col-sm-4">
                <h1>Donatur Pribadi</h1>

                <h5>
                    Untuk mendaftar sebagai donatur pribadi, anda tidak boleh terikat pada suatu yayasan dalam pembukaan dan pembinaan skema beasiswa, setiap skema beasiswa yang ditawarkan harus melalui proses verifikasi oleh pihak Universitas Indonesia
                    <br><br>
                    Silakan klik link dibawah ini untuk mendaftarkan diri
                </h5>

                <h4><strong><a class="btn btn-primary" href="{% url 'register:kategori' 2 %}">Daftar sebagai Donatur Pribadi</a></strong></h4>
            </div>

            <div class="col-sm-4">
                <h1>Donatur Yayasan</h1>

                <h5>
                    Pastikan yayasan anda terdaftar secara resmi sesuai hukum yang berlaku di Indonesia, dan masih aktif selama skema beasiswa masih berlangsung. Setiap skema beasiswa yang ditawarkan harus melalui proses verifikasi oleh pihak Universitas Indonesia
                    <br><br>
                    Silakan klik link dibawah ini untuk mendaftarkan diri
                </h5>
                <h4><strong><a class="btn btn-primary" href="{% url 'register:kategori' 3 %}">Daftar sebagai Donatur Yayasan</a></strong></h4>
            </div>
        </div>
    </div>
{% endblock %}

register/templates/register/register_donatur_pribadi.html
{% extends "melihat_informasi_beasiswa_aktif/layout/base.html" %}
{% block content %}
    <style>

        *{
            font-family: 'Droid Sans', sans-serif;
        }
        .main{
            text-align: center;
            min-height: 650px;
            padding-left: 250px;
            padding-right: 250px;
        }

        .main h2{
            font-size: 50px;
            margin-top: 0px;
            padding-top: 75px;
        }

        .font_form{
            font-size: 25px;
            margin-top: 25px;
        }

        .main form h5{
            font-size: 25px;
        }

        .main h5{
            font-size: 20px;
        }

    </style>

    <div class="main" style="padding-bottom: 50px">

            <div>
                <h2><strong>Pendaftaran Donatur Pribadi</strong></h2>
                <br><br>
                <h4>
                    Lengkapi semua data yang diperlukan, isian dengan tanda * wajib diisi.
                </h4>
            </div>


            <div style="text-align: left">

                <form style="font-size: 20px" action="{% url 'register:reg_dp' %}" method="POST">

                    {% csrf_token %}

                    <h5 class="font_form">Username*</h5>
                    <input type="text" name="username" required>

                    <h5 class="font_form">Password*</h5>
                    <input type="password" name="password" required>

                    <h5 class="font_form">Nomor Identitas*</h5>
                    <input type="number" name="no_id" required>

                    <h5 class="font_form">NIK*</h5>
                    <input type="number" name="nik" required>

                    <h5 class="font_form">Email*</h5>
                    <input type="email" name="email" required>

                    <h5 class="font_form">Nama Lengkap*</h5>
                    <input type="text" name="nama_lengkap" required>

                    <h5 class="font_form">NPWP*</h5>
                    <input type="number" name="npwp" required>

                    <h5 class="font_form">Nomor Telepon</h5>
                    <input type="number" name="no_telp" value="0">

                    <h5 class="font_form">Alamat Lengkap*</h5>
                    <input type="text" name="alamat" required>

                    <br><br>
                    <input type="submit" value = "Submit">
            </form>
            </div>


        </div>

{% endblock %}

register/templates/register/register_donatur_yayasan.html
{% extends "melihat_informasi_beasiswa_aktif/layout/base.html" %}
{% block content %}
    <style>

        *{
            font-family: 'Droid Sans', sans-serif;
        }
        .main{
            text-align: center;
            min-height: 650px;
            padding-left: 250px;
            padding-right: 250px;
        }

        .main h2{
            font-size: 50px;
            margin-top: 0px;
            padding-top: 75px;
        }

        .font_form{
            font-size: 25px;
            margin-top: 25px;
        }

        .main form h5{
            font-size: 25px;
        }

        .main h5{
            font-size: 20px;
        }

    </style>

    <div class="main" style="padding-bottom: 50px">

            <div>
                <h2><strong>Pendaftaran Donatur Yayasan</strong></h2>
                <br><br>
                <h4>
                    Lengkapi semua data yang diperlukan, isian dengan tanda * wajib diisi.
                </h4>
            </div>


            <div style="text-align: left">

                <form style="font-size: 20px" action="{% url 'register:reg_dy' %}" method="POST">

                    {% csrf_token %}

                    <h5 class="font_form">Username*</h5>
                    <input type="text" name="username" required>

                    <h5 class="font_form">Password*</h5>
                    <input type="password" name="password" required>

                    <h5 class="font_form">Nomor Identitas*</h5>
                    <input type="number" name="no_id" required>

                    <h5 class="font_form">Nama Yayasan*</h5>
                    <input type="text" name="nama_yayasan" required>

                    <h5 class="font_form">Nomor SK Yayasan*</h5>
                    <input type="number" name="no_sk" required>

                    <h5 class="font_form">Email*</h5>
                    <input type="email" name="email" required>

                    <h5 class="font_form">Nama CP*</h5>
                    <input type="text" name="nama_cp" required>

                    <h5 class="font_form">No Telp CP*</h5>
                    <input type="number" name="no_telp" value="0">

                    <h5 class="font_form">NPWP*</h5>
                    <input type="number" name="npwp" required>

                    <h5 class="font_form">Alamat Yayasan*</h5>
                    <input type="text" name="alamat" required>

                    <br><br>
                    <input type="submit" value = "Submit">
            </form>
            </div>


        </div>

{% endblock %}

register/templates/register/register_mahasiswa.html
{% extends "melihat_informasi_beasiswa_aktif/layout/base.html" %}
{% block content %}
    <style>

        *{
            font-family: 'Droid Sans', sans-serif;
        }
        .main{
            text-align: center;
            min-height: 650px;
            padding-left: 250px;
            padding-right: 250px;
        }

        .main h2{
            font-size: 50px;
            margin-top: 0px;
            padding-top: 75px;
        }

        .font_form{
            font-size: 25px;
            margin-top: 25px;
        }

        .main form h5{
            font-size: 25px;
        }

        .main h5{
            font-size: 20px;
        }

    </style>

    <div class="main" style="padding-bottom: 50px">

            <div>
                <h2><strong>Pendaftaran Mahasiswa</strong></h2>
                <br><br>
                <h4>
                    Lengkapi semua data yang diperlukan, isian dengan tanda * wajib diisi.
                </h4>
            </div>


            <div style="text-align: left">

                <form style="font-size: 20px" action="{% url 'register:reg_mhs' %}" method="POST">

                    {% csrf_token %}

                    <h5 class="font_form">Username*</h5>
                    <input type="text" name="username" required>

                    <h5 class="font_form">Password*</h5>
                    <input type="password" name="password" required>

                    <h5 class="font_form">NPM*</h5>
                    <input type="number" name="npm" required>

                    <h5 class="font_form">Email*</h5>
                    <input type="email" name="email" required>

                    <h5 class="font_form">Nama Lengkap*</h5>
                    <input type="text" name="nama_lengkap" required>

                    <h5 class="font_form">Nomor Telepon</h5>
                    <input type="number" name="no_telp" value="0">

                    <h5 class="font_form">Alamat Tempat Tinggal*</h5>
                    <input type="text" name="alamat_t" required>

                    <h5 class="font_form">Alamat Domisili*</h5>
                    <input type="text" name="alamat_d" required>

                    <h5 class="font_form">Instansi Bank*</h5>
                    <input type="text" name="instansi_bank" required>

                    <h5 class="font_form">Nomor Rekening*</h5>
                    <input type="number" name="no_rek" required>

                    <h5 class="font_form">Nama Pemilik*</h5>
                    <input type="text" name="nama_pemilik" required>

                    <br><br>
                    <input type="submit" value = "Submit">
            </form>
            </div>


        </div>
{% endblock %}