login_logout/urls.py
from django.conf.urls import url
from .views import index,auth_login, auth_logout

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^auth_login/$', auth_login, name="auth_login"),
    url(r'^auth_logout/$', auth_logout, name="auth_logout")

]

mendaftarkan_skema_beasiswa/urls.py
from django.conf.urls import url
from .views import index, daftarkan_beasiswa, pendaftaran_beasiswa, pendaftaran_beasiswa_dari_paket, daftarkan_beasiswa_dari_paket

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^beasiswa_baru', daftarkan_beasiswa, name='beasiswa_baru'),
    url(r'^daftar', pendaftaran_beasiswa, name='pendaftaran_beasiswa'),
    url(r'^paket_beasiswa', daftarkan_beasiswa_dari_paket, name='paket_beasiswa'),
    url(r'^tambah', pendaftaran_beasiswa_dari_paket, name='beasiswa_dari_paket'),
]

simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login_logout.urls as login
import register.urls as register
from login_logout.views import auth_logout
import melihat_informasi_beasiswa_aktif.urls as melihat_informasi_beasiswa_aktif
import mendaftarkan_skema_beasiswa.urls as mendaftarkan_skema_beasiswa
import daftar_calon_penerima_beasiswa.urls as daftar_calon_penerima_beasiswa
import tentukan_status_calon.urls as tentukan_status_calon

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^beasiswa_aktif/', include(('melihat_informasi_beasiswa_aktif.urls','melihat_informasi_beasiswa_aktif'), namespace='melihat-informasi-beasiswa-aktif')),
    url(r'^daftarkan_beasiswa/', include(('mendaftarkan_skema_beasiswa.urls', 'mendaftarkan_skema_beasiswa'), namespace='mendaftarkan-skema-beasiswa')),
    url(r'^$', RedirectView.as_view(url = "/beasiswa_aktif/", permanent = "true"), name = 'index'),
    url(r'^daftar-calon-penerima-beasiswa/', include(('daftar_calon_penerima_beasiswa.urls', 'daftar_calon_penerima_beasiswa'), namespace='daftar-calon-penerima-beasiswa')),
    url(r'^list-beasiswa/', include(('tentukan_status_calon.urls', 'tentukan_status_calon'), namespace='list-beasiswa')),
    url(r'^login/', include(('login_logout.urls', 'login'), namespace="login")),
    url(r'^logout/', auth_logout, name="logout"),
    url(r'^register/', include(('register.urls', 'register'),namespace="register"))
]

mendaftarkan_skema_beasiswa/models.py
from django.db import models
import datetime
# Create your models here.
class PaketBeasiswa(models.Model):
	kode = models.IntegerField(primary_key = True)
	nama_paket_beasiswa = models.CharField(max_length = 100, blank = False)
	jenis_paket_beasiswa = models.CharField(max_length = 20, blank = False)
	syarat_beasiswa = models.TextField(blank = False)

class Beasiswa(models.Model):
	kode_beasiswa = models.IntegerField(blank = False)
	nomor_urut = models.IntegerField(blank = False)
	tanggal_mulai_pendaftaran = models.DateField(auto_now = False, auto_now_add = False, blank = False, default=datetime.date.today)
	tanggal_tutup_pendaftaran = models.DateField(auto_now = False, auto_now_add = False, blank = False, default=datetime.date.today)

	class Meta:
		unique_together = ('kode_beasiswa', 'nomor_urut')

mendaftarkan_skema_beasiswa/forms.py
from django import forms
from .models import PaketBeasiswa
from django.utils.translation import ugettext as _

class PaketBeasiswa_Form(forms.Form):
	error = {
		'required' : 'Please fill in the blank'
	}
	attrs = {
		'class' : 'form-control'
	}
	CHOICES = (('Prestasi', 'Prestasi'),('Ekonomi', 'Ekonomi'),('Tugas Akhir', 'Tugas Akhir'))
	kode = forms.IntegerField(widget=forms.TextInput(attrs=attrs),required=True)
	nama_paket_beasiswa = forms.CharField(max_length = 100, widget=forms.TextInput(attrs=attrs), required=True)
	jenis_paket_beasiswa = forms.ChoiceField(choices=CHOICES, widget=forms.Select(attrs=attrs), required=True)
	deskripsi = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)
	syarat_beasiswa = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

class Beasiswa_Form(forms.Form):
	error = {
		'required' : 'Please fill in the blank'
	}
	attrs = {
		'class' : 'form-control'
	}
	# kode_beasiswa = forms.ModelChoiceField(widget=forms.Select(attrs=attrs), queryset=PaketBeasiswa.objects.values('kode'))
	nomor_urut = forms.IntegerField(widget=forms.TextInput(attrs=attrs),required=True)
	# tanggal_mulai_pendaftaran = forms.DateField(initial='YYYY-DD-MM', widget=forms.DateInput(attrs=attrs), required=True)
	# tanggal_tutup_pendaftaran = forms.DateField(initial='YYYY-DD-MM', widget=forms.DateInput(attrs=attrs), required=True)

mendaftarkan_skema_beasiswa/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.db import connection
from .forms import PaketBeasiswa_Form, Beasiswa_Form
from .models import PaketBeasiswa, Beasiswa
from tentukan_status_calon.models import SkemaBeasiswa, SkemaBeasiswaAktif
import datetime
# Create your views here.
response = {}
cursor = connection.cursor()
def index(request):
	if("username" not in request.session):
		return HttpResponseRedirect(reverse('login_logout:index'))
	else:
		username = request.session['username']
		response['username'] = username
		query = "SELECT * FROM pengguna WHERE username='"+username+"'"
		cursor.execute(query)
		select = dictfetchall(cursor)
		print(select[0]['role']) #ini cetak donatur
		# cek dia donatur atau bukan(!IMPORTANT)

		role = select[0]['role']
		if role == 'donatur':
			response['allowed'] = True
			response['donatur'] = True
			response['mahasiswa'] = False
		elif role == 'mahasiswa':
			response['allowed'] = False
			response['mahasiswa'] = True
			response['donatur'] = False
		else :
			response['allowed'] = False
			response['mahasiswa'] = False
			response['donatur'] = False
		return render(request, 'mendaftarkan_skema_beasiswa/index.html', response)

def pendaftaran_beasiswa(request):
	response['kode_double'] = False
	response['beasiswaBaru_form'] = PaketBeasiswa_Form
	html = 	'mendaftarkan_skema_beasiswa/beasiswaBaru.html'
	return render (request, html, response)

def pendaftaran_beasiswa_dari_paket(request):
	cursor.execute('SELECT kode from simbion.skema_beasiswa')
	response['kode']=dictfetchall(cursor)
	response['not_unique'] = False
	response['beasiswa_form'] = Beasiswa_Form
	html = 	'mendaftarkan_skema_beasiswa/beasiswaDariPaket.html'
	return render (request, html, response)

def daftarkan_beasiswa(request):
	form = PaketBeasiswa_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['kode'] = request.POST['kode']
		cursor.execute("SELECT * from simbion.skema_beasiswa where kode='"+response['kode']+"'")
		select = cursor.fetchone()
		if(select is not None):
			print("KEMBAR")
			response['kode_double'] = True
			response['beasiswaBaru_form'] = PaketBeasiswa_Form
			html ='mendaftarkan_skema_beasiswa/beasiswaBaru.html'
			return render(request, html, response)
		else:
			print('GAKEMBAR')
			response['nama_paket_beasiswa'] = request.POST['nama_paket_beasiswa']
			response['jenis_paket_beasiswa'] = request.POST['jenis_paket_beasiswa']
			response['syarat_beasiswa'] = request.POST['syarat_beasiswa']
			response['deskripsi'] = request.POST['deskripsi']

			username = request.session['username']
			query = "SELECT * FROM donatur WHERE username='"+username+"'"
			cursor.execute(query)
			select = dictfetchall(cursor)
			print(select[0]['nomor_identitas'])
			response['no_identitas_donatur'] = select[0]['nomor_identitas']

			query = "INSERT INTO SKEMA_BEASISWA(kode, nama, jenis, deskripsi, no_identitas_donatur) VALUES ("+response['kode']+", '"+response['nama_paket_beasiswa']+"', '"+response['jenis_paket_beasiswa']+"', '"+response['deskripsi']+"', "+response['no_identitas_donatur']+")"
			cursor.execute(query)

			query = "INSERT INTO SYARAT_BEASISWA(kode_beasiswa, syarat) VALUES ("+response['kode']+", '"+response['syarat_beasiswa']+"')"
			cursor.execute(query)

			return HttpResponseRedirect('/daftarkan_beasiswa/')
	else:
		return HttpResponseRedirect('/daftarkan_beasiswa/')


def daftarkan_beasiswa_dari_paket(request):
	form = Beasiswa_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['kode_beasiswa'] = request.POST['kode_beasiswa']
		response['nomor_urut'] = request.POST['nomor_urut']
		response['tanggal_mulai_pendaftaran'] = request.POST['tanggal_mulai_pendaftaran']
		response['tanggal_tutup_pendaftaran'] = request.POST['tanggal_tutup_pendaftaran']

		cursor.execute("SELECT * from simbion.skema_beasiswa_aktif where kode_skema_beasiswa='"+response['kode_beasiswa']+"' AND no_urut='"+response['nomor_urut']+"'")
		select = cursor.fetchone()
		print(select)
		if(select is not None):
			response['not_unique'] = True
			response['beasiswa_form'] = Beasiswa_Form
			html ='mendaftarkan_skema_beasiswa/beasiswaDariPaket.html'
			return render(request, html, response)
		else:
			periode = response['tanggal_mulai_pendaftaran']+" s/d "+response['tanggal_tutup_pendaftaran']
			status = 'Buka'
			query = "INSERT INTO SKEMA_BEASISWA_AKTIF(kode_skema_beasiswa, no_urut, tgl_mulai_pendaftaran, tgl_tutup_pendaftaran, periode_penerimaan, status, jumlah_pendaftar, total_pembayaran) VALUES ("+response['kode_beasiswa']+","+response['nomor_urut']+", '"+response['tanggal_mulai_pendaftaran']+"', '"+response['tanggal_tutup_pendaftaran']+"', '"+periode+"', '"+status+"', "+'0'+','+'0'+")"
			cursor.execute(query)

			return HttpResponseRedirect('/daftarkan_beasiswa/')
	else:
		return HttpResponseRedirect('/daftarkan_beasiswa/')

def dictfetchall(cursor):
	"Return all rows from a cursor as a dict"
	columns = [col[0] for col in cursor.description]
	return [
		dict(zip(columns, row))
		for row in cursor.fetchall()
	]

mendaftarkan_skema_beasiswa/templates/mendaftarkan_skema_beasiswa/partials/footer.html
{% load static %}
<div class="bg-dark text-white" style="background-color: #0275d8">
    <div class="container">
      <div class="row">
        <div class="p-4 col-md-3">
          <h2 class="mb-4 text-secondary">Simbion
            <br>
          </h2>
          <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
        <div class="p-4 col-md-3">
          <h2 class="mb-4 text-secondary">Directory</h2>
          <ul class="list-unstyled">
            <a href="#" class="text-white">Home</a>
            <br>
            <a href="#" class="text-white">About us</a>
            <br>
            <a href="#" class="text-white">Our services</a>
            <br>
            <a href="#" class="text-white">Stories</a>
          </ul>
        </div>
        <div class="p-4 col-md-3">
          <h2 class="mb-4">Contact</h2>
          <p>
            <a href="#" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-phone"></i>1234567890</a></p>
          <p>
            <a href="#" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-envelope-o"></i>admin@simbion.com</a></p>
          <p>
            <a href="#" class="text-white" target="_blank">
              <i class="fa d-inline mr-3 fa-map-marker text-secondary"></i>Universitas Indonesia</a></p>
        </div>
        <div class="p-4 col-md-3">
          <h2 class="mb-4 text-light">Subscribe</h2>
          <form>
            <fieldset class="form-group text-white">
              <label for="exampleInputEmail1">Get our newsletter</label>
              <input type="email" class="form-control" placeholder="Enter email"> </fieldset>
            <button type="submit" class="btn btn-outline-secondary">Submit</button>
          </form>
        </div>
      </div>
      <div class="row" >
        <div class="col-md-12 mt-3">
          <p class="text-center text-white">© Copyright Hanif Agung Prayoga - Ibnu Sofian Firdaus - Kianutama Radianur - All rights reserved. </p>
        </div>
      </div>
    </div>
  </div>

mendaftarkan_skema_beasiswa/templates/mendaftarkan_skema_beasiswa/partials/header.html
{% load static %}
<style media="screen">
  .navbar{
    height: 50px;
    background-color: #0275d8;  
  }
  .navbar-light .navbar-nav .active>.nav-link, .navbar-light .navbar-nav .nav-link.active, .navbar-light .navbar-nav .nav-link.open, .navbar-light .navbar-nav .open>.nav-link {
    color: white;
  }
  .navbar-light .navbar-nav .nav-link {
    color: white;
}

@media only screen and (max-width: 768px){
  .navbar-nav{
    background-color: white;
  }
  .navbar-light .navbar-nav .nav-link {
    color: black;
}

}
</style>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="z-index: 1;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <a class="nav-link" href="{% url 'melihat-informasi-beasiswa-aktif:index' %}" style="color: white;">Home</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      {% if mahasiswa %}
      <li class="nav-item">
        <a class="nav-link" href="#">Lihat Pengumuman</a>
      </li>
      </ul>
      </div>
      {% if username %}
      <a class="nav-link pull-right btn btn-danger" style="color: white" href="{% url 'login:auth_logout' %}" onclick="return confirm('Are you sure?')">Log out</a>
      {% endif %}
      {% endif %}
      {% if donatur %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'list-beasiswa:index' %}">List Beasiswa</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mendaftarkan-skema-beasiswa:index' %}">Daftarkan Beasiswa</a>
      </li>
      </ul>
      </div>
      <a class="nav-link pull-right btn btn-danger" style="color: white" href="{% url 'login:auth_logout' %}" onclick="return confirm('Are you sure?')">Log out</a>
      {% endif %}
</div>
</nav>